import Header from '@/components/Header'
import Footer from '@/components/Footer'
import './globals.css'
import type { Metadata } from 'next'
import Provider from './Provider'


export const metadata: Metadata = {
  title: 'Player',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,

}: {
  children: React.ReactNode
}) {
  return (
    <html lang="kr">
      <body>
        <Provider>
          {children}
        </Provider>
      </body>
    </html>
  )
}
